/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.ImageIcon;

/**
 *
 * @author Usuario
 */
public class CityMall extends javax.swing.JFrame {

    /**
     * Creates new form CityMall
     */
    public CityMall() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/img/618304700_1280x720.jpg")).getImage() );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTanda = new javax.swing.JButton();
        btnPelí = new javax.swing.JButton();
        btnSala = new javax.swing.JButton();
        btnVenta = new javax.swing.JButton();
        btnCant = new javax.swing.JButton();
        btnProgra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cinemark");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTanda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-zona-horaria-40.png"))); // NOI18N
        btnTanda.setText("Tanda");
        btnTanda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTanda.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnTanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTandaActionPerformed(evt);
            }
        });
        jPanel1.add(btnTanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 80, 70));

        btnPelí.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-película-40.png"))); // NOI18N
        btnPelí.setText("Películas");
        btnPelí.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPelí.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnPelí.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPelíActionPerformed(evt);
            }
        });
        jPanel1.add(btnPelí, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 80, 70));

        btnSala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-audiencia-40.png"))); // NOI18N
        btnSala.setText("Sala");
        btnSala.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSala.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 80, 70));

        btnVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-promedio-2-40.png"))); // NOI18N
        btnVenta.setText("Venta");
        btnVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVenta.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaActionPerformed(evt);
            }
        });
        jPanel1.add(btnVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 80, 70));

        btnCant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-terminal-punto-de-venta-40.png"))); // NOI18N
        btnCant.setText("Cantidad");
        btnCant.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCant.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCantActionPerformed(evt);
            }
        });
        jPanel1.add(btnCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 80, 70));

        btnProgra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-ventana-de-navegación-40.png"))); // NOI18N
        btnProgra.setText("Programación");
        btnProgra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProgra.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnProgra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrograActionPerformed(evt);
            }
        });
        jPanel1.add(btnProgra, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 110, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alajuela_1600x900.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPelíActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPelíActionPerformed
        // TODO add your handling code here:
        frmPeliculas peli=new frmPeliculas(this,false);
        peli.setVisible(true);
    }//GEN-LAST:event_btnPelíActionPerformed

    private void btnSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalaActionPerformed
        // TODO add your handling code here:
        frmSala sala=new frmSala(this,false);
        sala.setVisible(true);
    }//GEN-LAST:event_btnSalaActionPerformed

    private void btnTandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTandaActionPerformed
        // TODO add your handling code here:
        frmTanda tanda=new frmTanda(this,false);
        tanda.setVisible(true);
    }//GEN-LAST:event_btnTandaActionPerformed

    private void btnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaActionPerformed
        // TODO add your handling code here:
        frmVenta venta=new frmVenta(this,false);
        venta.setVisible(true);
    }//GEN-LAST:event_btnVentaActionPerformed

    private void btnCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantActionPerformed
        // TODO add your handling code here:
        frmCantidad cant=new frmCantidad(this,false);
        cant.setVisible(true);
    }//GEN-LAST:event_btnCantActionPerformed

    private void btnPrograActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrograActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrograActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CityMall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CityMall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CityMall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CityMall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CityMall().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCant;
    private javax.swing.JButton btnPelí;
    private javax.swing.JButton btnProgra;
    private javax.swing.JButton btnSala;
    private javax.swing.JButton btnTanda;
    private javax.swing.JButton btnVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
