/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Datos.DatosPelicula;
import Logica.Pelicula;
import com.sun.glass.events.KeyEvent;
import java.awt.Image;
import java.io.IOException;
import java.nio.file.CopyOption;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class frmAgregaPelicula extends javax.swing.JDialog {
    DatosPelicula almacenaPeli;
    String idImg="";
    int posi, operac;
    /**
     * Creates new form frmAgregaPelicula
     */
    public frmAgregaPelicula(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public frmAgregaPelicula(java.awt.Frame parent, boolean modal, DatosPelicula almPeli, int pos, int operacion) {
        super(parent, modal);
        initComponents();
        this.almacenaPeli = almPeli;
        this.posi = pos;
        this.operac = operacion;
        if (this.operac == 2) {
            idImg = almacenaPeli.getRegistro(pos).getImagen();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblimagen = new javax.swing.JLabel();
        btnsubir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txttitulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbgenero = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtduraccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbclasificaccion = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbidioma = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        rdb3d = new javax.swing.JRadioButton();
        rdb2d = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        btncancelar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 26, 26));

        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 75, 26));

        lblimagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/defaultPic.png"))); // NOI18N
        lblimagen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblimagen.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(lblimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 121, 127));

        btnsubir.setText("Subir Imagen");
        btnsubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubirActionPerformed(evt);
            }
        });
        jPanel1.add(btnsubir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 121, -1));

        jLabel3.setText("Clasificacción:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 80, 26));

        txttitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttituloActionPerformed(evt);
            }
        });
        jPanel1.add(txttitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 290, 26));

        jLabel4.setText("Genero:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 50, 26));

        cmbgenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Accion", "Comedia", "Drama", "Terror" }));
        cmbgenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbgeneroActionPerformed(evt);
            }
        });
        jPanel1.add(cmbgenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 120, 30));

        jLabel5.setText("Titulo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 40, 26));

        txtduraccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtduraccionKeyTyped(evt);
            }
        });
        jPanel1.add(txtduraccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 120, 30));

        jLabel6.setText("Tipo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 50, 30));

        cmbclasificaccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "TP", "+12", "+15", "+18" }));
        jPanel1.add(cmbclasificaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 120, 30));

        jLabel7.setText("Duracción:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 60, 26));

        cmbidioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Español", "Ingles", "SubTituladad" }));
        jPanel1.add(cmbidioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 120, 30));

        jLabel8.setText("Idioma:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 60, 30));

        buttonGroup1.add(rdb3d);
        rdb3d.setText("3D");
        jPanel1.add(rdb3d, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        buttonGroup1.add(rdb2d);
        rdb2d.setText("2D");
        jPanel1.add(rdb2d, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cancelar-suscripción-48.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-guardar-48.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnlimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-escoba-48.png"))); // NOI18N
        btnlimpiar.setText("Limpiar Campo");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttituloActionPerformed

    private void cmbgeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbgeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbgeneroActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        // TODO add your handling code here:
        txtId.setText("");
        txttitulo.setText("");
        cmbgenero.setSelectedIndex(0);
        txtduraccion.setText(null);
        cmbidioma.setSelectedIndex(0);
        cmbclasificaccion.setSelectedIndex(0);
        rdb2d.setSelected(true);
        lblimagen.setIcon(null);
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        String valTipo = "";
        if (!txtId.getText().equals("") && !txttitulo.getText().equals("")
                && cmbgenero.getSelectedIndex() != 0 && cmbidioma.getSelectedIndex() != 0
                && cmbclasificaccion.getSelectedIndex() != 0 && (rdb2d.isSelected() || rdb3d.isSelected())) {
            if (rdb2d.isSelected()) {
                valTipo = rdb2d.getText();
            } else if (rdb3d.isSelected()) {
                valTipo = rdb3d.getText();
            }
            int durac;
            if (txtduraccion.getText().equals("")) {
                durac = 0;
            } else {
                durac = Integer.parseInt(txtduraccion.getText());
            }
            Pelicula peliObj = new Pelicula(Integer.parseInt(txtId.getText()), txttitulo.getText(),
                    String.valueOf(cmbgenero.getSelectedItem()), durac,
                    String.valueOf(cmbidioma.getSelectedItem()), String.valueOf(cmbclasificaccion.getSelectedItem()),
                    valTipo, idImg);
            if (idImg.equals("")){
                peliObj.setImagen("defaultPic.png");
            }
            if (operac == 1) {   //Se guarda un nuevo registro
                if (!almacenaPeli.yaExiste(Integer.parseInt(txtId.getText()))) {

                    if (almacenaPeli.insertPelicula(peliObj)) {
                        JOptionPane.showMessageDialog(this, "Registro Almacenado");
                    } else {
                        JOptionPane.showMessageDialog(this, "Vector lleno, Borre Registros");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "El ID ya Existe");
                }
            } else { //Editar un registro existente
                if (almacenaPeli.editaPelicula(posi, peliObj)) {
                    JOptionPane.showMessageDialog(this, "Registro Editado");
                    txtId.setEditable(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Error de Edición");
                }
            }
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Faltan Datos");
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
        // TODO add your handling code here:
        int tecla;
        tecla = evt.getKeyChar();
        if (!Character.isDigit(tecla) && tecla != KeyEvent.VK_SPACE && tecla != KeyEvent.VK_BACKSPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdKeyTyped

    private void txtduraccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtduraccionKeyTyped
        // TODO add your handling code here:
        int tecla;
        tecla = evt.getKeyChar();
        if (!Character.isDigit(tecla) && tecla != KeyEvent.VK_SPACE && tecla != KeyEvent.VK_BACKSPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_txtduraccionKeyTyped

    private void btnsubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubirActionPerformed
        // TODO add your handling code here:
        String destino;
        String origen;
        if (!txtId.getText().equals("")) {
            idImg = "img" + txtId.getText() + ".jpg";
            Selectordearchivo chooser = new Selectordearchivo(null, true);
            chooser.setVisible(true);

            origen = chooser.path;
            String rutaFondo = System.getProperty("java.class.path") + "\\img\\" + idImg;
            String rut[] = rutaFondo.split(";");
            destino = rut[1];

            Path FROM = Paths.get(origen);
            Path TO = Paths.get(destino);
            //sobreescribir el fichero de destino,si ya existe y copiar los atributos incluyendo los permisos rwx
            CopyOption[] options = new CopyOption[]{
                StandardCopyOption.REPLACE_EXISTING,
                StandardCopyOption.COPY_ATTRIBUTES};

            try {
                Files.copy(FROM, TO.toAbsolutePath(), options);
            } catch (IOException ex) {

            }
            ImageIcon imagen = new ImageIcon(getClass().getResource("/img/" + idImg));
            ImageIcon imgAjust = new ImageIcon(imagen.getImage().getScaledInstance(
                    lblimagen.getWidth(), lblimagen.getHeight(), Image.SCALE_DEFAULT));
            imgAjust.getImage().flush();
            lblimagen.setIcon(imgAjust);
        } else {
            JOptionPane.showMessageDialog(this, "Se Debe Establecer el ID");
        }
    }//GEN-LAST:event_btnsubirActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        ImageIcon imagen;
        Pelicula peliObj;
        if (operac == 2) {
            txtId.setEditable(false);
            peliObj = almacenaPeli.getRegistro(posi);
            txtId.setText(String.valueOf(peliObj.getId()));
            txttitulo.setText(peliObj.getTitulo());
            cmbgenero.setSelectedItem(peliObj.getGenero());
            txtduraccion.setText(String.valueOf(peliObj.getDuraccion()));
            cmbidioma.setSelectedItem(peliObj.getIdioma());
            cmbclasificaccion.setSelectedItem(peliObj.getClasif());
            if (rdb2d.getText().equals(peliObj.getTipo())) {
                rdb2d.setSelected(true);
            } else {
                rdb3d.setSelected(true);
            }
//            if (idImg.equals("")) {
//                idImg = "defaultPic.png";
//            }
            imagen = new ImageIcon(getClass().getResource("/img/" + peliObj.getImagen()));
            ImageIcon imgAjust = new ImageIcon(imagen.getImage().getScaledInstance(lblimagen.getWidth(), lblimagen.getHeight(), Image.SCALE_DEFAULT));
            imgAjust.getImage().flush();
            lblimagen.setIcon(imgAjust);
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAgregaPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAgregaPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAgregaPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAgregaPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmAgregaPelicula dialog = new frmAgregaPelicula(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnsubir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbclasificaccion;
    private javax.swing.JComboBox<String> cmbgenero;
    private javax.swing.JComboBox<String> cmbidioma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblimagen;
    private javax.swing.JRadioButton rdb2d;
    private javax.swing.JRadioButton rdb3d;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtduraccion;
    private javax.swing.JTextField txttitulo;
    // End of variables declaration//GEN-END:variables
}
